name: deployment

on:
  push:
  workflow_dispatch:

jobs:
  validation:
      name: Branch validation
      runs-on: ubuntu-latest
      steps:
        - name: Check branch name
          run: |
            if [[ "${{ github.ref }}" == "refs/heads/master" ]] || [[ "${{ github.ref }}" =~ ^refs/heads/feature/.*$ ]] || [[ "${{ github.ref }}" =~ ^refs/heads/bug/.*$ ]] ; then
              echo "Branch naming is correct!"
            else
              echo "Invalid branch name! Correct format: 'feature/<branch-name>' or 'bug/<branch-name>'"
              exit 1
            fi
  build:
    name: build
    needs: validation
    runs-on: ubuntu-latest
    outputs:
      build-tag: ${{ steps.build-image.outputs.tag }}
      deployment-targets: ${{ steps.set-targets.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        id: gradle-build
        continue-on-error: false
        with:
          arguments: :build
          build-root-directory: .
