name: "PR Title Check action"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^[A-Z][a-zA-Z ]*$'
          error_message: 'PR title should start with an uppercase letter and should not contain non-alphabetic characters or digits.'
          ignore_case: false
          validate_only_modified_files: false